'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Message
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KatabanBusinessLogic.Message", GetType(Message).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to バリエーションによって選択出来ないストロークも表示されていますのでご注意下さい。.
        '''</summary>
        Public Shared ReadOnly Property M001() As String
            Get
                Return ResourceManager.GetString("M001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 形番引当最終時にＯＫボタンで可否判別となります。.
        '''</summary>
        Public Shared ReadOnly Property M002() As String
            Get
                Return ResourceManager.GetString("M002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 最小ストロークは異面取付状態で判別しています。.
        '''</summary>
        Public Shared ReadOnly Property M003() As String
            Get
                Return ResourceManager.GetString("M003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ※ＳＭＧシリーズへの切換えをお願いします。.
        '''</summary>
        Public Shared ReadOnly Property M004() As String
            Get
                Return ResourceManager.GetString("M004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ※ＳＣＳ２シリーズへの切換えをお願いします。.
        '''</summary>
        Public Shared ReadOnly Property M005() As String
            Get
                Return ResourceManager.GetString("M005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to （製作可能範囲：[1]　～　[2]）.
        '''</summary>
        Public Shared ReadOnly Property M006() As String
            Get
                Return ResourceManager.GetString("M006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 技術より採番された数値を入力してください(ミックスの場合)。.
        '''</summary>
        Public Shared ReadOnly Property M007() As String
            Get
                Return ResourceManager.GetString("M007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to オプション記号を選択する時は、先頭のボックスから順番にお選び下さい。.
        '''</summary>
        Public Shared ReadOnly Property M008() As String
            Get
                Return ResourceManager.GetString("M008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ｴｱﾕﾆｯﾄとして使用される際は、CXU30-VEを推奨します。必要有効断面積をご確認ください。.
        '''</summary>
        Public Shared ReadOnly Property M009() As String
            Get
                Return ResourceManager.GetString("M009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ※NAD,PAD(センサ分離タイプ)は、生産終了の対象外です。.
        '''</summary>
        Public Shared ReadOnly Property M010() As String
            Get
                Return ResourceManager.GetString("M010", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
