'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class RLayout
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("S0202.RLayout", GetType(RLayout).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Public Shared ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Japanese.
        '''</summary>
        Public Shared ReadOnly Property Japanese() As String
            Get
                Return ResourceManager.GetString("Japanese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Korean.
        '''</summary>
        Public Shared ReadOnly Property Korean() As String
            Get
                Return ResourceManager.GetString("Korean", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log off.
        '''</summary>
        Public Shared ReadOnly Property LogOff() As String
            Get
                Return ResourceManager.GetString("LogOff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Menu.
        '''</summary>
        Public Shared ReadOnly Property Menu() As String
            Get
                Return ResourceManager.GetString("Menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Model Search.
        '''</summary>
        Public Shared ReadOnly Property ModelSearch() As String
            Get
                Return ResourceManager.GetString("ModelSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Part No. Search.
        '''</summary>
        Public Shared ReadOnly Property PartNoSearch() As String
            Get
                Return ResourceManager.GetString("PartNoSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chinese.
        '''</summary>
        Public Shared ReadOnly Property SimplifiedChinese() As String
            Get
                Return ResourceManager.GetString("SimplifiedChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specification input.
        '''</summary>
        Public Shared ReadOnly Property SpecificationInput() As String
            Get
                Return ResourceManager.GetString("SpecificationInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tset.
        '''</summary>
        Public Shared ReadOnly Property test() As String
            Get
                Return ResourceManager.GetString("test", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parts-Number Searching System.
        '''</summary>
        Public Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taiwanese.
        '''</summary>
        Public Shared ReadOnly Property TraditionalChinese() As String
            Get
                Return ResourceManager.GetString("TraditionalChinese", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
